#! /bin/csh

#set this to purge modules (if any) and to get system host module ("GMU Hopper)
module purge
module load hosts/hopper

#These are system-dependent modules (not needed if using AnaCONDA virtual environment (recommended)
#module load ncl  #NCL must support  "wrapit77" version for swamp.f and weight.f (use conda env)
#module load gdal/3.2.0-q7  #GDAL must support  PRISM bil-->netcdf conversion    (use conda env)
